### ISSUE TITLE
can

### ISSUE THREAD

**Issue by xjustbmw** [MaxKravt/WiFi-Modbus-TCPtoRTU#2]
i read on tasmota git that you also have a mqtt to can converter ?
can you share the code?

thanks

**Comment by MaxKravt** [comment]
No. I don`t have converter MQTT - ModbusRTU.  The idea is interesting. I think there are already ready-made solutions. 
PS. If you don`t find converter, may by write one.

**Comment by Jojo-A** [comment]
@MaxKravt Hi Max and thank you a ton for your work regarding the Modbus-Converter! I could not find any other project which is that universal and complete. I have is running on an ESP8266 as a direct gateway between my SDM630 and Home Assistant, because Home Assistant supports Modbus natively. IIRC I modified your project so that I kicked out the telnet stuff and added the webserver from the project "WifiManager". Thanks a ton!

@xjustbmw maybe you mean something from me? I think I mentioned my MQTT-to-CAN gateway somewhere - but IIRC not on Tasmota... you have a link?
